# This file is a template, and might need editing before it works on your project.
# Template project: https://gitlab.com/pages/jekyll
# Docs: https://docs.gitlab.com/ce/pages/
image: ruby:2.6

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - gem install bundler
  - gem install jekyll -v '3.6.2'
  - gem install minima -v '2.0'
  - gem install jekyll-watch -v '1.5.1'
  - gem install jekyll-sitemap
  - gem install jekyll-feed
  - gem install jekyll-seo-tag
  - gem install tzinfo-data
  - bundle install

test:
  stage: test
  script:
    - bundle exec jekyll build -d test
  artifacts:
    paths:
      - test
  except:
    - master

pages:
  stage: deploy
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - master
